### ISSUE TITLE
mining software

### ISSUE THREAD

**Issue by hhdllhflower** [bitcoinx-project/bitcoinx#10]
is there any mining software?
or any mining pool?

**Comment by fjlxl88** [comment]
我也想要采矿软件，还有需要采矿的教程，我希望得到你们的帮助，谢谢！

**Comment by Tarlzlee** [comment]
Hi, when will you guys release the first version of mining software？

**Comment by fjlxl88** [comment]
I didn't get the mining software.

**Comment by fjlxl88** [comment]
I also want mining software, and a tutorial that needs mining. I hope to get your help, thank you!

**Comment by Tarlzlee** [comment]
兄弟， 当前BCX的挖矿软件还没发呢，但是软件发布时间也没有公布。目前只有一个钱包软件可以安装

**Comment by fjlxl88** [comment]
谢谢兄弟的提醒。什么时候可以挖矿就通知我一下，我的微信是：1030312357，谢谢你！

**Comment by Tarlzlee** [comment]
好的，不必客气。我们互相提醒吧，呵呵。晚点加你微信哈，我微信号Tarlzlee

**Comment by fjlxl88** [comment]
我已经添加了你的微信，谢谢！

**Comment by ygrdkl** [comment]
Tarlzlee，我也加你微信哈，我微信号rzlt119，感谢哈。。。

**Comment by 15616232924** [comment]
I also want to mine software and tutorials that need to be mined. I hope to get your help, thank you!

**Comment by 15616232924** [comment]
I also want to mine software and tutorials that need to be mined. I hope to get your help, thank you!qq:2739089794

**Comment by qqonline** [comment]
有没有兄弟建个微信群？

大家多相互提醒下。

**Comment by Tarlzlee** [comment]
大家加我微信Tarlzlee，我们已经有了一个BCX的大群，里面有很多兄弟可以一起探讨

**Comment by tw132899** [comment]
官方为啥不直接弄个矿池！让大家挖

**Comment by tr0812** [comment]
BCX是不是用的Blake2b算法？是不是蚂蚁A3可以挖这个。

**Comment by ankur112** [comment]
is there any mining software???
