### ISSUE TITLE
Importprivkey doesn't work in console

### ISSUE THREAD

**Issue by themuzzman** [bitcoinx-project/bitcoinx#11]
wallet rescans, shows no balance.

**Comment by ho1to** [comment]
bcx is fork at 49888 height, If you have bitcoin after this height, importing the private key will not have bcx.

**Comment by ho1to** [comment]
bcx is fork at 49888 height, If you have btc after this height, importing the private key will not have bcx.

**Comment by themuzzman** [comment]
I had BTC at the fork date.  I was able to get all other forks from
December.  2 questions.

1).  After you import the private key.  Do I need to add witness address or
do anything else?

2).  Is there a block explorer or way to check my public keys and verify
these balances?

**Comment by ho1to** [comment]
1) witness address we have not tested

2) the block explorer neeed a third party to provide
