### ISSUE TITLE
how to synchronizate wallet software?

### ISSUE THREAD

**Issue by longwang8115** [bitcoinx-project/bitcoinx#13]
HI,
1,I have two wallet softwares. one is for testintenet, other is normal.  they are both have years behind. why like this? which one should be will work?
2. I let software working  all morning. It doesn't have any change. how to sychronizate wallet soon? Do they have data package download?

**Comment by valyriasteel** [comment]
@longwang8115 you need to use the [bcx wallet](https://github.com/bitcoinx-project/bitcoinx/releases) instead of else.
