### ISSUE TITLE
Synchronizing Using Copy of Bitcoin Blockchain

### ISSUE THREAD

**Issue by NoWay426** [bitcoinx-project/bitcoinx#16]
I already have a copy of the blockchain from running a Bitcoin Core node. I have copied the blocks & chainstate folders into the BitcoinX directory and am reindexing using the Core data, but obviously they will diverge at the fork. How do I sync up to BitcoinX without having to re-download the whole blockchain? Can I use invalidateblock at the time of the fork?

**Comment by valyriasteel** [comment]
@NoWay426 in theory, you can use `invalidateblock` back to the best height at 498888, but will get warning involves the chain work each time you receive a new block from BitcoinX.
