### ISSUE TITLE
Peers List?

### ISSUE THREAD

**Issue by NoWay426** [bitcoinx-project/bitcoinx#18]
Does anybody have a list of known working BitcoinX Peers that I can manually add? My client is only connected to 1-2 peers.

**Comment by tnkmt** [comment]
I got these:

    $ ./bitcoinx-cli getpeerinfo | grep \"addr\" | cut -d \: -f 2- | cut -d \" -f 2 | grep \:
    192.169.227.48:9003
    166.62.117.163:9003
    [2001:41d0:1004:24a5::]:9003
    51.255.94.165:9003
    162.212.156.23:9003
    [2402:1f00:8001:284::]:9003
    120.131.13.83:9003
    120.92.19.190:9003

How can I export all peers from my `peers.dat` file?
