### ISSUE TITLE
When to ore mine?

### ISSUE THREAD

**Issue by jimmysm** [bitcoinx-project/bitcoinx#19]
When to ore mine?

**Comment by LinLinchen** [comment]
deng

**Comment by tr0812** [comment]
deng

**Comment by maldiohead** [comment]
deng deng WTF

**Comment by ho1to** [comment]
https://www.reddit.com/r/BCXofficial/comments/7vdls5/bcx_official_mining_guide_and_mining_pools/?utm_source=reddit-android
