### ISSUE TITLE
when running 'make' from 'depends' it downloads binaries - is it safe?

### ISSUE THREAD

**Issue by tnkmt** [bitcoinx-project/bitcoinx#20]
Why it downloads binaries (boost) instead of source? Does it check signatures of the binaries?

It would be safer if only source code is downloaded.

**Comment by neuralbayes** [comment]
The depends are safe, if you don't want to build the package to install on the other platform, you need't run make from depends

**Comment by sefo64** [comment]
Hi

Thanks for  email
I will judge  will report soon.
Whn does not like with Blockchein.

Thanks again
