### ISSUE TITLE
 "status": "valid-fork"

### ISSUE THREAD

**Issue by tnkmt** [bitcoinx-project/bitcoinx#21]
What is this "valid-fork"? Bug or a feature?

    $ ./bitcoinx-cli getchaintips
    [
      {
        "height": 512402,
        "hash": "000000000006b44c23948f0785ae40b03ad521ae6d8ec09997955cd7a9d0027e",
        "branchlen": 0,
        "status": "active"
      }, 
      {
        "height": 512342,
        "hash": "0000000000041e4c8fab5b616142f21f3936cf58c950c0ccb0988837ceb1ec6f",
        "branchlen": 1,
        "status": "valid-fork"
      }
    ]

Version (built from source):

    ./bitcoinxd --version
    BitcoinX Core Daemon version v0.16.1

<img src="https://lh3.googleusercontent.com/-W2hziitn7ks/VubCKAEG2iI/AAAAAAAAAK0/kBKQEHnc_oA/s530-p/bug-ang-feature.jpg" alt="" />

**Comment by HAWKEYE81** [comment]
Is this saying BCX is a valid fork

**Comment by fjlxl88** [comment]
Can we use CPU、GPU mining BCX now?

**Comment by tnkmt** [comment]
It now says 512422 for the height of the 'active' branch. I assume that it's working as intended.

    [
      {
        "height": 512422,
        "hash": "00000000001b742d78d253d55f4e11c21ab5e3a1fa83781d7860187f46b2d869",
        "branchlen": 0,
        "status": "active"
      },
      {
        "height": 512342,
        "hash": "0000000000041e4c8fab5b616142f21f3936cf58c950c0ccb0988837ceb1ec6f",
        "branchlen": 1,
        "status": "valid-fork"
      }
    ]




> Do nodes store all the branches from entire blockchain history?

They will store all branches that they know of so long as the block headers of each branch are fully valid.

The way that Bitcoin Core nodes (and all node software based upon Bitcoin Core) work is that they will ask for an receive a block header before asking for the actual block itself. Using the headers, the node builds a headers chain. So if a block header is valid (i.e. it has a valid proof of work and connects to known previous block headers), it will be stored and added to the chainstate. In this way, a node can know of and keep track of all branches of the blockchain without having the block itself.

Even if a headers chain does not have the most work, it will still be kept around forever and kept track of. Although blocks for that headers chain will not be requested, if any peers have that chain as their actual blockchain and the headers are completely valid, it will still be known to a peer and kept track of.

If a headers chain suddenly begins having invalid block headers, the chain of valid headers will still be kept and tracked; the invalid headers extending that won't be.

Source: https://bitcoin.stackexchange.com/questions/61106/does-full-node-store-all-valid-forks-and-alternative-blocks-from-blockchain-hi
