### ISSUE TITLE
syncing too slow

### ISSUE THREAD

**Issue by hhdllhflower** [bitcoinx-project/bitcoinx#3]
any static node please?
and what algorithm for mining?

**Comment by ho1to** [comment]
We working on this, so many node for syning

**Comment by linjunjj** [comment]
how to mining？

**Comment by hellomotow** [comment]
@ho1to Can you please list your synced nodes?

**Comment by ho1to** [comment]
@linjunjj  blake2b

@hhdllhflower @hellomotow 

sync nodes just add in fixed nodes，more nodes need community
be involved together

**Comment by hellomotow** [comment]
@ho1to Thanks for your reply. Could you help put together a node list?

**Comment by ho1to** [comment]
@hellomotow 

```
192.169.153.174 
192.169.154.185 
166.62.117.163 
120.131.13.83
192.169.227.48
120.131.13.249
```
