### ISSUE TITLE
syncing will not happen, wallet does not do anything, help?

### ISSUE THREAD

**Issue by dextronomous** [bitcoinx-project/bitcoinx#84]
guys what is the latest version of this wallet, 16.3 ok got it, then why do i have the biggest issue on syncin this wallet.
can anyone add new node(s) or anything like that peers list dat file etc. would appreciate it a lot.

**Comment by Master0ne** [comment]
I was just wondering the same thing. [Website](https://bcx.org/) down, [Explorer](https://bcx.info/) down, are there even any nodes left, and if yes and some addresses emerge, how to add to BitcoinX Core v0.16.3.0?
